server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # /api 요청은 백엔드 서비스로 프록시
    location /api/ {
        proxy_pass http://taskflow-backend-svc/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
